# This docker-compose file uses secrets to manage sensitive information like passwords.
services:
  koodo-reader:
    image: ghcr.io/koodo-reader/koodo-reader:master
    container_name: koodo-reader
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - SERVER_USERNAME=${SERVER_USERNAME:-admin}
      - SERVER_PASSWORD_FILE=${SERVER_PASSWORD_FILE:-my_secret}
      - ENABLE_HTTP_SERVER=false
    volumes:
      # 使用主机目录（推荐）
      - /opt/uploads:/app/uploads
    secrets:
      - my_secret
secrets:
  my_secret:
    file: ./my_secret.txt
